inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

# This allows a longer LineLength and ignores cuke definitions
Layout/LineLength:
  Max: 140
  IgnoredPatterns:
    - '^Given'
    - '^When'
    - '^Then'

# Our gemspec and Spec files contain huge blocks and need to
Metrics/BlockLength:
  Exclude:
    - './spec/**/*_spec.rb'
    - 'site_prism.gemspec'

# We are a DSL, so we occasionally need to use `.set_` prefixes on our DSL names
Naming/AccessorMethodName:
  Enabled: false

# Stylistic preference to make the RSpec tests flow better
RSpec/MessageSpies:
  EnforcedStyle: receive

# This is a better style, and should be the default IMO
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
