language: ruby

sudo: required

dist: xenial

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

env:
  - browser=chrome
  - browser=firefox

gemfile:
  - Gemfile
  - gemfiles/Gemfile.low_spec
  - gemfiles/Gemfile.webdriver_alpha

addons:
  chrome: stable
  firefox: latest

services:
  - xvfb

script:
  - bundle exec rake

branches:
  only:
    - main
